name: Push dist

on:
  push:
    branches:
      - experimental

jobs:
  push-dist:
    name: Push dist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yarn --frozen-lockfile
      - uses: kategengler/put-built-npm-package-contents-on-branch@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pack-command: yarn pack
